name: Cargo Test
on:
  push:
    branches:
      - master
    paths:
      - core/**
      - server/**
      - client-cli/**
      - client/**
      - api-types/**
      - contracts/**
      - event-sinks/**
      - Cargo.toml
      - Cargo.lock
      - .cargo
      - .github/workflows/cargo*
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  RUST_LOG: ${{ vars.RUST_LOG }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Lint check
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
